In [ ]:
# 布尔型数组
# 除了整数型数组和浮点型数组，还有一种有用的数组类型 -- 布尔型数组

In [ ]:
# 7.1 创建布尔型数组
# 由于Numpy的主要数据类型是整数型数组和浮点型数组，因此布尔型数组的产生离不开：
# 大于 > ，大于等于 >= ，等于 == ，不等于 != ，小于 < ，小于等于 <=

In [12]:
# 先与数组和系数做比较，以产生布尔类型数组：
import numpy as np

air = np.arange(1,13).reshape(3,4)
print(air)

print(air >=4)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [15]:
# 同维数组做比较，以产生布尔型数组

aaa = np.arange(1,9)
bbb = np.flipud(aaa)

print(aaa)
print(bbb)

print(aaa > bbb)
print(aaa < bbb)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
[False False False False  True  True  True  True]
[ True  True  True  True False False False False]


In [ ]:
# 还可以同时比较多个条件，Python基础里，同时检查多个条件使用的与、或、非是：
# and 、 or 、not
# 但是Numpy中使用的与、或、非是：
# & 、｜、～

In [17]:
aa = np.arange(1,17)
print(aa)

# 多个条件
print(aa < 10)|(aa >16)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ True  True  True  True  True  True  True  True  True False False False
 False False False False]


TypeError: unsupported operand type(s) for |: 'NoneType' and 'bool'

In [ ]:
# 7.2 布尔型数组中Ture的数量
# 有三个关于Ture数量的有用函数，分别是：
np.sum()
np.any()
np.all()

In [29]:
# 在np.sum()函数：统计布尔类型数组里Ture的个数。
import numpy as np

# 创建一个形状为10000的标准正态分布数组
iii = np.random.normal(0,1,10000)

# 统计该分布中绝对值小于1的元素个数
num = np.sum(np.abs(iii) < 1)
print(num) 

# np.abs(iii) < 1 可以替换(iii>-1)&(iii<1)
# 此外，最终统计的数量为6814，其概率近似为0.6827，符合统计学的3σ准则

6835


In [30]:
# 在np.any()函数：只要布尔类型数组里含有一个及以上的Ture，就返回Ture

aaa = np.arange(1,10)
bbb = np.flipud(aaa)

print(aaa)
print(bbb)

# 统计这两个数组是否有共同元素
print(np.any(aaa == bbb))

# 含有共同元素的是5

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
True


In [31]:
# 在np.all()函数：当布尔类型数组全是Ture时，才返回Ture

# 模拟英语六级的成绩，创建100000个样本

ccc = np.random.normal(500,70,100000)

# 判断是否所有考生的分手都高于425

print(np.all(ccc>425))

# 500 - 3 * 70

False


In [35]:
# 7.3 布尔型数组作为掩码
# 若一个普通数组和一个布尔类型数组的维度相同，可以将布尔型数组作为普通数组的掩码，
# 这样可以对普通数组中的元素作筛选

# 筛选出数组中大于，等于或小于某个数字的元素
ar = np.arange(1,19).reshape(6,3)
print(ar)

# 数组与数字做比较
print(ar < 10)

# 筛选出ar > 6 的元素
print(ar[ar > 6])
# 这个矩阵进行掩码操作后，退化为了向量


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]
 [False False False]
 [False False False]]
[ 7  8  9 10 11 12 13 14 15 16 17 18]


In [38]:
# 筛选出数组逐元素比较的结果

ccc = np.arange(1,10)
ddd = np.flipud(ccc)
print(ccc)
print(ddd)

# 同维度数组作比较
print(ccc > ddd)

# 筛选出ccc > ddd 位置上的元素
print(ccc[ccc > ddd])
print(ddd[ccc > ddd])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[False False False False False  True  True  True  True]
[6 7 8 9]
[4 3 2 1]


In [ ]:
# 7.4 满足条件的元素所在位置
# 假设一个很长的数组，我们想知道满足某一个条件的元素们所在的索引位置
# 此时使用：
np.where()

In [51]:
# 模拟英语六级成绩的随机数组，取10000个样本
fff = np.random.normal(500,70,1000)

# 找出六级成绩超过650的元素所在位置
print(np.where(fff>650))

# 找出六级成绩最高分的元素所在位置
print(np.where(fff == np.max(fff)))

# np.where()函数的输出看起来比较怪异，它是输出了一个元组，
# 元组的第一个元素是“满足条件的元素所在位置”；
# 第二个是数组类型，可忽略掉

(array([ 85, 243, 409, 461, 475, 518, 541, 549, 620, 725, 754, 793, 921,
       950]),)
(array([409]),)
