In [ ]:
# 2.1 创建指定的数组

# 当明确知道数组每一个元素的具体数值时，可以使用：
np.array()
# 此函数，将python列表转化为numpy数组

In [3]:
import numpy as np

# 创建一维数组 —— 向量
ari = np.array([1,2,3])
print(ari)

# 创建二维数组 —— 行矩阵
ari_i = np.array([[1,2,3]])
print(ari_i)

# 创建二维数组 —— 列矩阵
ari_ii = np.array([[1],[2],[3]])
print(ari_ii)

# 创建二维数组 —— 矩阵
ari_iii = np.array([[1,2,3],[4,5,6]])
print(ari_iii)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 2.2 创建递增数组
# 递增数组使用：
np.arange()
# 此函数进行创建（ arange 全称是 array_range)

In [7]:
import numpy as np

# 递增数组 1 
ari = np.arange(10) # 从0开始，到10之前结束
print(ari)

# 递增数组 2 
ari_i = np.arange(10,20) # 从10开始，到20之前结束
print(ari_i)

# 递增数组 3
ari_ii = np.arange(1,21,2) # 从1开始，到21之前结束，步长为2
print(ari_ii)

# 如过需要浮点数数组

ari_iii = np.arange(10.0) 
air = 1.0 * np.arange(10)
air_i = 0.0 + np.arange(10)
print(ari_iii)
print(air)
print(air_i)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# 2.3 创建同值数组

# 需要创建同值数组时，使用：
np.zeros()
np.ones()

In [11]:
import numpy as np

# 全0数组
ari = np.zeros(3)
print(ari)

# 形状为3的向量

# 全1的数组
air = np.ones((1,3))
print(air)

# 形状为（1，3）的矩阵

# 全3.14数组
air_i = 3.14 * np.ones((2,3))
print(air_i)

# 形状为（2，3）的矩阵

# 函数输出的并不熟整数型的数组，这可能是为了避免插入的浮点数被截断，所以将其设定为浮点型数组

[0. 0. 0.]
[[1. 1. 1.]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [ ]:
# 2.4 创建随机数组

# 有时候需要创建随机数组，那么可以使用：
np.random
# 这一系列函数


In [13]:
import numpy as np

# 0-1 均匀分布的浮点型随机数组

air = np.random.random(5)
print(air)

# 创建60-100范围内均匀分布的3行3列随机数组：

air_i = (100-60)*np.random.random((3,3)) + 60
print(air_i)

# 0-1均匀分布乘以40，它的范围就变成了0-40
# 在加上60，它的范围就变成了60-100

[0.11075538 0.64264358 0.02042178 0.58249104 0.14361325]
[[87.05229463 70.83436543 78.85139404]
 [81.69389664 68.81293797 79.96175103]
 [93.48163579 98.62125922 89.19341561]]


In [18]:
# 整数型随机数组
import numpy as np

air = np.random.randint(10,100,(1,15))
print(air)

# 形状为（1，15）的矩阵
# 该函数需要额外输入范围参数，本例的范围是10-100

# ===========

air_i = (90 * np.random.random((1,15))).astype(int) + 10
print(air_i)

air_ii = 90 * np.random.random((1,15)) + 10
air_ii = air_ii.astype(int)
print(air_ii)

# 要注意运算顺序！！！

[[61 47 52 54 77 47 21 14 75 32 41 98 94 55 77]]
[[80 74 89 14 68 23 65 76 93 52 29 65 35 65 55]]
[[62 84 84 69 85 21 57 42 70 19 34 35 50 36 66]]


In [21]:
# 服从正态分布的随机数组
import numpy as np

arr = np.random.normal(0,1,(2,3)) # 形状为（2，3）的二维矩阵
print(arr)

# 在np.random.normal()中要传入三个参数
# 第一个参数 - 均值
# 第二个参数 - 标准差
# 第三个参数 - 形状



arri = np.random.normal(2,2,(2,3)) 
print(arri)

[[ 1.6437881   0.61048376  0.09862776]
 [-1.5064656  -0.59603616 -0.22539117]]
[[ 0.70922136  2.93561698  5.37260268]
 [-0.31915282  2.67255491  3.28521706]]


In [ ]:
# 该函数需要额外输入正态函数，本例中均值为0，标准差为1，
# 在这种情况下，可以直接使用：
np.random.randn()
# 这一函数，只需传入形状参数即可

In [20]:
import numpy as np
npp = np.random.randn(2,5)
print(npp)

[[ 0.38238717 -0.48891094  0.32811224  0.40730005  0.45627537]
 [-0.48714437 -1.28484921 -1.11734518  0.28525466 -0.88197086]]
