In [ ]:
# 3.1 访问数组元素

# 与Python列表一致，访问Numpy数组元素时使用中括号，索引由0开始。

In [4]:
# (1) 访问向量 

import numpy as np

air = np.arange(2,10,2)
print(air)

print(air[2]) # 正着访问
print(air[-2]) # 倒着访问

# 修改数组元素
air[1] = 40
print(air)

[2 4 6 8]
6
6
[ 2 40  6  8]


In [12]:
# (2) 访问矩阵
import numpy as np

arr = np.array([[1,24,3],[45,6,7]])
print(arr)

# 访问元素
print(arr[0,1],arr[1,-3])

# 修改元素
arr[0,1] = 2
print(arr)


# 要注意，浮点数插入到整数数组时，会被截断

[[ 1 24  3]
 [45  6  7]]
24 45
[[ 1  2  3]
 [45  6  7]]


In [ ]:
# 3.2 花式索引：
# 花式索引（Fancy indexing)

# 逗号在矩阵里区分行与列，在这里新增一个功能，且不会与矩阵里的逗号混淆

In [14]:
# (1) 向量的花式索引

import numpy as np

arri = np.arange(0,90,10)
print(arri)

# 花式索引
print(arri[[0,2]])

# 花式索引需要两层中括号，[ [0,0] ]


[ 0 10 20 30 40 50 60 70 80]
[ 0 20]


In [19]:
# (2)矩阵的花式索引
import numpy as np

arri = np.arange(1,17).reshape(4,4)
print(arri)

# 花式索引
print(arri[[0,1],[1,0]])
print(arri[[0,1,2],[2,1,0]]) # 一一对应
# 第0行，第2列 ，第1行，第1列 ， 第2行，第0列

# 修改数组元素
arri[[0,2,3],[2,0,1]] = 16
print(arri)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[2 5]
[3 6 9]
[[ 1  2 16  4]
 [ 5  6  7  8]
 [16 10 11 12]
 [13 16 15 16]]


In [22]:
# 3.3 访问数组的切片

# (1) 向量的切片
# 向量与列表的切片操作完全一致

import numpy as np
arri = np.arange(17)

# 当明确知道从第x个元素切到第y个元素：
print(arri)
print(arri[1:4]) #从索引[1]开始，切到索引[4]之前
print(arri[1: ]) #从索引[1]开始，切到结尾
print(arri[ :12]) # 从数组开头开始，切到索引[12]之前

# 当明确切除的组的开头与结尾：
print(arri)
print(arri[6:-5])  # 切除开头6个和结尾5个
print(arri[4: ]) # 切除开头4个
print(arri[ :-11]) # 切除结尾15个

# 当明确隔几个元素采样一次时：
print(arri)
print(arri[ :  : 1]) #每1个元素采样一次
print(arri[ :  : 4]) #每4个元素采样一次
print(arri[1:-2:2]) # 切除头1个，尾2个，每2个元素采样一次

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[1 2 3]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 6  7  8  9 10 11]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16]
[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  4  8 12 16]
[ 1  3  5  7  9 11 13]


In [25]:
# (2) 矩阵的切片

import numpy as np
arr = np.arange(1,21).reshape(5,4)
print(arr)

print(arr[1:3,1:-1]) # 行从1开始切，切到3之前，（1-2）；列从前后各第一列开始切

# 跳跃采样
print(arr[::2,::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]
 [17 19]]


In [31]:
# (3) 提取矩阵的行

import numpy as np

arr = np.arange(1,21).reshape(4,5)
print(arr)

print (arr[1,:]) # 提取第1行，列全要

print(arr[1:3,:]) # 提取1至2行，列全要

# 考虑到代码的简洁，当提取矩阵的某几行时可以简写（但提取列时候不可以）
print(arr[2])


print(arr[1][3]) # 提取第1行，在提取这行的第3个元素，不推荐！！！

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
9


In [32]:
# (4) 提取矩阵的列

import numpy as np

arr = np.arange(1,21).reshape(4,5)
print(arr)

print(arr[:,2]) # 提取第2列（注意，输出的向量）

print(arr[:,1:3]) # 提取1至2列


# 取某一个单独的列，出来的结果是一个向量，只是为了节省空间

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [42]:
# 提取一个列矩阵

import numpy as np

arr = np.arange(1,19).reshape(3,6)
print(arr)

cut = arr[:,3] # 提取第3列
print(cut)

cut = cut.reshape((1,-1)) # 升级为矩阵
print(cut)

print(cut.T) # 转置操作 .T 只对矩阵有用

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[ 4 10 16]
[[ 4 10 16]]
[[ 4]
 [10]
 [16]]


In [4]:
# 3.4 数组切片仅是试图
# (1) 数组切片仅是试图

# Numpy 数组的切片仅仅是原数组的一个试图。换言之，Numpy切片并不会创建新的变量。

import numpy as np 

arr = np.arange(10)
print(arr)

cut = arr[ : 3] #创建arr的切片cut
print(cut)

cut[0] = 20 #对切片的数值进行修改
print(cut)

print(arr) #原数组也被修改

# 深度学习中，为节省内存，将多次使用 arr[:]= <表达式> 来替换 arr = <表达式>


[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[20  1  2]
[20  1  2  3  4  5  6  7  8  9]


In [ ]:
# (2)备份切片为新变量
# 如果真的需要为切片创建新的变量（这种情况很稀少），使用：
.copy()

In [5]:
import numpy as np

arr = np.arange(13) # 创建一个0-12的向量
print(arr)

copy = arr[ :3].copy() # 创建arr的拷贝切片
print(copy)

copy[0] = 40 # 对拷贝切片的数值进行修改
print(copy)

print(arr) #原数组不变

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]
[40  1  2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
# 3.5 数组赋值仅是绑定
# (1) 数组赋值仅是绑定
#  与Numpy数组的切片一样，Numpy数组完整的赋值给另一个数组，也只是绑定。
# 换言之，Numpy 数组之间的赋值并不会创建新的变量。

import numpy as np

arr = np.arange(13)
print(arr)
 
arr_i = arr  # 把数组arr 赋值给另一个 arr_i
print(arr_i)

arr_i[2] = 66 #修改数组
print(arr_i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1 66  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# (2)复制数组为新变量
# 如果真的需要赋给一个新的数组，使用：
.copy()

In [7]:
import numpy as np

arr = np.arange(10)
print(arr)

ar = arr.copy()  # 把数组arr拷贝赋值给另一个数组ar
print(ar)

ar[5] = 88  # 修改数组5
print(ar)

print(arr) # 查看原数组

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 88  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
