In [3]:
# 数组的运算
# 5.1 数组与系数之间的运算
import numpy as np
arr = np.arange(1,19).reshape(3,6)
print(arr)

print(arr + 10) # 加

print(arr - 10) # 减

print(arr * 10) # 乘

print(arr / 10) # 除

print(arr ** 2) # 平方

print(arr // 4) # 取整

print(arr % 4) # 取余
# 当一个矩阵和一个系数进行运算的时候，系数会作用到矩阵的每一个元素
# 在除法中，不管除以多少，最后都以浮点型数组输出

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[11 12 13 14 15 16]
 [17 18 19 20 21 22]
 [23 24 25 26 27 28]]
[[-9 -8 -7 -6 -5 -4]
 [-3 -2 -1  0  1  2]
 [ 3  4  5  6  7  8]]
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]
 [130 140 150 160 170 180]]
[[0.1 0.2 0.3 0.4 0.5 0.6]
 [0.7 0.8 0.9 1.  1.1 1.2]
 [1.3 1.4 1.5 1.6 1.7 1.8]]
[[  1   4   9  16  25  36]
 [ 49  64  81 100 121 144]
 [169 196 225 256 289 324]]
[[0 0 0 1 1 1]
 [1 2 2 2 2 3]
 [3 3 3 4 4 4]]
[[1 2 3 0 1 2]
 [3 0 1 2 3 0]
 [1 2 3 0 1 2]]


In [12]:
# 5.2 数组与数组之间的运算
# 同维度数组之间的运算即对应元素之间的运算，矩阵和向量与系数之间的操作与之相同。

import numpy as np
air = np.arange(-1,-10,-1).reshape(3,3)
print(air)
air2 = -air
print(air2)

print(air + air2) # 加

print(air - air2) # 减

print(air * air2) # 乘
# 乘法是遵循对应元素相乘的 - 逐元素乘积，如何实现现代的“矩阵级乘法，在后面会提到。

print(air / air2) # 除 ， 只要有除法运算符，整数型一定会变成浮点型数组

print(air ** air2) # 平方


[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]
[[ -1  -4  -9]
 [-16 -25 -36]
 [-49 -64 -81]]
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
[[        -1          4        -27]
 [       256      -3125      46656]
 [   -823543   16777216 -387420489]]


In [ ]:
# 5.3 广播 （向量或者行矩阵/列矩阵，都有一个维度为1，维度为1的那个维度会被广播，去适配另一个矩阵的形状）
# 5.2是同形状数组之间的逐元素运算，此章节讲解不同形状的数组之间的的运算：
# 二维数组之内的情况下，不同形状的数组之间的运算有以下规则：
# 1. 如果是向量与矩阵之间的运算，向量自动升级为行矩阵； 且只能升级为行矩阵，不能升级为列矩阵
# 2. 如果某矩阵是行矩阵或者列矩阵，则其称为广播，以适配另一个矩阵的形状

In [17]:
# (1) 向量被广播
# 当一个形状为（x,y)的矩阵与一个向量做运算时，要求该向量的形状必须为y，运算时向量会自动升级成形状为（1，y）的行矩阵
# 该形状为（1，y）的行矩阵再自动被广播为形状为（x，y）的矩阵，这样就与另一个矩阵的形状适配了。

import numpy as np

# 向量
arr = np.array([-100,0,100])
print(arr)

# 矩阵
arr2 = np.random.random((6,3))
print(arr2)

# 广播：
print(arr * arr2)
# -100就会沿着垂直的方向去广播，0会沿着垂直方向去广播，100一样，然后二者之间的形状就匹配了
# arr2这个随机矩阵，它的第一列全部都乘 -100，第二列全部乘 0，第三列全部乘100


[-100    0  100]
[[0.58313038 0.1667611  0.0739695 ]
 [0.03660977 0.26682784 0.21668965]
 [0.15646449 0.78235562 0.22305511]
 [0.45021323 0.9465178  0.62928633]
 [0.38626509 0.48994773 0.56912315]
 [0.13388943 0.5531964  0.01304042]]
[[-58.31303777   0.           7.39694978]
 [ -3.66097706   0.          21.6689649 ]
 [-15.64644878   0.          22.30551064]
 [-45.02132311   0.          62.92863303]
 [-38.626509     0.          56.91231495]
 [-13.38894348   0.           1.30404238]]


In [21]:
# (2)列矩阵被广播
# 当一个形状为(x,y)的矩阵与另一个矩阵做运算时，要求该列矩阵的形状必须为(x,1),
# 该形状为(x,1)的列矩阵再自动被广播为形状为(x,y)的矩阵，这样就与另一个矩阵的形状适配了。

import numpy as np

# 列矩阵
arr = np.arange(4).reshape(4,1)
print(arr)

# 矩阵
ar = np.ones((4,3))
print(ar)

# 广播：
print(arr * ar)
# 列矩阵会沿着水平方向去广播，去广播3次

[[0]
 [1]
 [2]
 [3]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [25]:
# (3)行矩阵与列矩阵同时被广播
# 当一个形状为(1,y)的行矩阵与一个形状为(x,1)的列矩阵做运算时，
# 这两个矩阵都会被自动广播为形状为(x,y)的矩阵，这样就互相适配了

import numpy as np

# 向量
arr = np.arange(4)
print(arr)

# 列矩阵
arri = np.arange(4).reshape(4,1)
print(arri)

# 广播
print(arr * arri)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
