In [ ]:
# 6.1 矩阵乘积
# 前一章的乘法都是“逐元素相乘”，这里介绍线性代数中的矩阵乘积，
# 只需要使用：
np.dot()
# 当矩阵乘积中混有向量时，根据需求，其可充当行矩阵，也可充当列矩阵，但是混有向量时输出结果必为向量》


In [7]:
# (1) 向量与向量的乘积
# 设两个向量的形状按前后顺序分别是5以及5，从矩阵乘法的角度
# (1,5)*(5,1)=(1,1)，因此输出的应该是形状为1的向量
import numpy as np

ar = np.arange(5)
ar2= np.arange(5)
print(ar)
print(ar2)

print(ar*ar2)
print(np.dot(ar,ar2)) #所以就是ar和ar2乘积相加的和


[0 1 2 3 4]
[0 1 2 3 4]
[ 0  1  4  9 16]
30


In [11]:
# (2)向量与矩阵的乘积
# 设向量的形状是5，矩阵的形状是（5，3）。从矩阵乘法的角度，由（1，5）*（5，3）=（1，3），因此输出的应该是形状为3的向量
import numpy as np
aa = np.arange(5)
bb = np.arange(15).reshape(5,3)
print(aa)
print(bb)

# 矩阵乘积
print(np.dot(aa,bb))

[0 1 2 3 4]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 90 100 110]


In [14]:
# (3) 矩阵与向量的乘积
# 设矩阵的形状是（3，5），向量的形状是5。从矩阵乘法的角度，有（3，5）*（3，1）= （3，1）
# 因此输出的应该是形状为3的向量
import numpy as np

air = np.arange(15).reshape(3,5)
ai = np.arange(5)

print(air)
print(ai)

print(np.dot(air,ai))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[ 30  80 130]


In [16]:
# (4) 矩阵与矩阵的乘积
# 设两个矩阵的形状按前后顺序分别为（5，2）以及（2，8）。
# 从矩阵乘法的角度，有（5，2）*（2，8）= （5，8）的矩阵

import numpy as np

a = np.arange(10).reshape(5,2)
b = np.arange(16).reshape(2,8)

print(a)
print(b)

print(np.dot(a,b))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[  8   9  10  11  12  13  14  15]
 [ 24  29  34  39  44  49  54  59]
 [ 40  49  58  67  76  85  94 103]
 [ 56  69  82  95 108 121 134 147]
 [ 72  89 106 123 140 157 174 191]]


In [18]:
# 6.2 数学函数
# Numpy设计了很多的数学函数，这里举例了其中最重要，最常见的几个。
import numpy as np

# 绝对值函数 - np.abs()
av = np.array([-10,0,10])
absv = np.abs(av)

print(av)
print(absv)

[-10   0  10]
[10  0 10]


In [19]:
# 三角函数
theta = np.arange(3)* np.pi / 2 
sinv = np.sin(theta)
cosv = np.cos(theta)
tanv = np.tan(theta)

print(theta) # 原数组
print(sinv) # 正弦值
print(cosv) # 余弦值
print(tanv) # 正切值

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [20]:
# 指数函数
x = np.arange(1,4)

print(x) 
print(np.exp(x)) #e^x
print(2**x) # 2^x
print(10**x) # 10^x

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]
[2 4 8]
[  10  100 1000]


In [21]:
# 对数函数
d = np.array([1,10,100,1000])

print(d)
print(np.log(d)) # ln(d)
print(np.log(d)/ np.log(2)) #log2(d)
print(np.log(d)/ np.log(10)) #log10(d)

[   1   10  100 1000]
[0.         2.30258509 4.60517019 6.90775528]
[0.         3.32192809 6.64385619 9.96578428]
[0. 1. 2. 3.]


In [22]:
# 6.3 聚合参数
# 聚合很有用，这里用矩阵演示。向量与之一致，但是没有axis参数
# 以下在注释中介绍了6个最重要的聚合函数，其用法一致，仅演示其中3个
import numpy as np

In [ ]:
# 最大值函数
np.max()

# 最小值函数
np.min()

In [24]:
ar = np.random.random((2,3))
print(ar)

print(np.max(ar,axis=0)) # 按维度一求最大值
print(np.min(ar,axis=1)) # 按维度二求最大值
print(np.max(ar)) #整体求最大值
print(np.min(ar)) #整体求最小值

[[0.7998857  0.00103189 0.27350907]
 [0.5444816  0.23463301 0.88775956]]
[0.7998857  0.23463301 0.88775956]
[0.00103189 0.23463301]
0.8877595619227517
0.0010318852240162046


In [ ]:
# 求和函数
np.sum()

# 求积函数
np.prod()

In [26]:
ari = np.arange(10).reshape(2,5)

print(ari)
print(np.sum(ari,axis=0)) # 按维度一求合
print(np.sum(ari,axis=1)) # 按维度二求合
print(np.prod(ari)) # 整体乘积
print(np.sum(ari)) # 整体求合

[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 5  7  9 11 13]
[10 35]
0
45


In [ ]:
# 均值函数
np.mean()

# 标准差函数
np.std()

In [27]:
arr = np.arange(10).reshape(2,5)

print()
print(np.mean(arr,axis=0)) # 按维度一求平均值
print(np.mean(arr,axis=1)) # 按维度二求平均值
print(np.mean(arr)) #整体求平均
 


[2.5 3.5 4.5 5.5 6.5]
[2. 7.]
4.5


In [ ]:
# 当axis=0时，最终结果与每一行的元素个数一致
# 当axis=1时，最终结果与每一行的元素个数一致

# 考虑到大型数据组难免有缺失值，以上聚合函数碰到缺失值时会报错，
# 因此，出现了聚合函数的安全版本，即计算时忽略缺失值：
np.nansum()
np.nanprod()
np.nanmean()
np.nanstd()
np.nanmax()
np.nanmin()