In [ ]:
# 数组的变形
# 4.1 数组的转置
# 数组的转置方法为：
.T
# 只对矩阵有效，因此遇到向量要先将其转化为矩阵。

In [3]:
# (1) 向量的转置
import numpy as np

ar = np.arange(1,7)
print(ar)

arr = ar.reshape((1,-1)) #升级为矩阵
print(arr)

arri = arr.T # 行矩阵的转置
print(arri)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [10]:
# (2) 矩阵的转置
# 列矩阵的转置：

import numpy as np
arr = np.arange(4).reshape(4,1)  #创建列矩阵
print(arr)

arri = arr.T # 列矩阵的转置
print(arri) #结果为行矩阵

# 矩阵的转置

ar = np.arange(6).reshape(2,3)
print(ar)

ar1 = ar.T  #矩阵的转置
print(ar1)

[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [ ]:
# 4.2 数组的反转
# 数组的翻转方法有两个：
# 1. 一个是上下翻转，表示up-down
np.flipud()
# 2. 另一个是左右翻转，表示left—right
np.fliplr()
# 在数学中，向量并不是横着排，而是竖着排的

In [11]:
# (1) 向量的翻转
import numpy as np

ari = np.arange(17)
print(ari)

ud = np.flipud(ari) #翻转向量
print(ud)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [2]:
# (2) 矩阵的翻转
import numpy as np

ari = np.arange(1,17).reshape(4,4)
print(ari)

# 左右翻转
lr = np.fliplr(ari)
print(lr)

# 上下翻转
ud = np.flipud(ari)
print(ud)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
# 4.3 数组的重塑
# 想要重塑数组的形状，需要用到：
.reshape()
# 如过给定了其他维度的数值，剩下的一个维度可以填写 -1，让他自己去算：
# 比如把一个5行6列的矩阵重塑为3行10列的举证，当列的参数10告诉它，行的参数直接用-1来替代，它会自己去用30除以10来计算。

In [9]:
# (1) 向量的变形
import numpy as np

arr = np.arange(2,12)
print(arr)

ari = arr.reshape(2,5) #变形为矩阵
print(ari)

# (2) 矩阵的变形
ar = np.array([[1,3,5,7],[2,4,6,8]])
print(ar)

aaa = ar.reshape(8) # 变形为向量 ，可以直接写入 -1
print(aaa)

bbb = ar.reshape(1,8) #变形为矩阵
print(bbb)

[ 2  3  4  5  6  7  8  9 10 11]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[1 3 5 7]
 [2 4 6 8]]
[1 3 5 7 2 4 6 8]
[[1 3 5 7 2 4 6 8]]


In [12]:
# 4.4 数组的拼接
# (1) 向量的拼接
# 两个向量的拼接，将得到一个新的加长版向量
np.concatenate([],[])


[1 2 3] [4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np

aaa = np.array([1,2,3])
bbb = np.array([4,5,6])
print(aaa,bbb)

# 拼接
ccc = np.concatenate([aaa,bbb])
print(ccc)

In [20]:
# (2) 矩阵的拼接
# 两个矩阵可以按不同的维度进行拼接，但拼接时必须注意维度的吻合。

import numpy as np

aaa = np.array([[1,1,1],[2,2,2]])
bbb = np.array([[3,4,5],[6,7,8]])
print(aaa,bbb)

# 按第一个维度（行）拼接
ccc = np.concatenate([aaa,bbb]) # 默认参数 axis=0 ,增加行的方向进行拼接
print(ccc)

# 按第二个维度（列）拼接
ddd = np.concatenate([aaa,bbb],axis=1) # 如果 axis=1，那就是按照列的方向进行拼接
print(ddd)

# 最后要说明的是，向量和矩阵不能进行拼接，必须先把向量升级为矩阵！！！

[[1 1 1]
 [2 2 2]] [[3 4 5]
 [6 7 8]]
[[1 1 1]
 [2 2 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1 3 4 5]
 [2 2 2 6 7 8]]


In [22]:
# 4.5 数组的分裂
# (1) 向量的分裂
# 向量分裂，将得到若干个更短的向量

import numpy as np
iii = np.arange(10,100,10)
print(iii)

# 分裂数组
aa,bb,cc = np.split(iii,[2,8]) 
print(aa,bb,cc)


[10 20 30 40 50 60 70 80 90]
[10 20] [30 40 50 60 70 80] [90]


In [ ]:
np.split()
# 在此函数中，给出的第二个参数[2,8],表示索引[2]和索引[8]的位置截断

In [25]:
# (2) 矩阵的分裂
# 矩阵的分裂同样可以按不同的维度进行，分裂出来的均为矩阵
import numpy as np

ar = np.arange(1,9).reshape(2,4)
print(ar)

# 按第一个维度（行）分裂
aaa,bbb = np.split(ar,[1]) #默认参数axis=0
print(aaa,'\n\n',bbb)  # 注意输出的是矩阵

# 按第二维度（列）分裂
ccc,ddd,eee = np.split(ar,[2,4],axis=1)
print(ccc,'\n\n',ddd,'\n\n',eee)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]] 

 [[5 6 7 8]]
[[1 2]
 [5 6]] 

 [[3 4]
 [7 8]] 

 []
