In [ ]:
# 数组基础
# "np" - import numpy as np

# 1.1
# Numpy 数组简单分为 整数型数组 和 浮点型数组


In [1]:
# 创建整数型数组

import numpy as np

arri = np.array([1,2,3])
print(arri)

[1 2 3]


In [2]:
# 创建浮点型数组

import numpy as np
arrii = np.array([1.2,3,4.5,6])
print(arrii)

# 当列表中只要含有一个浮点型数字的时候，那么转化成数组的时候，整个数组都是浮点型数组

[1.2 3.  4.5 6. ]


In [ ]:
# 使用print输出Numpy数组后，元素之间没有逗号，
# 这有两个好处：
# 1. 可以与 python 的列表区分开来。
# 2. 避免逗号与小数点之间的混淆。


# 同化定理
#  1. 往整数型数组里插入浮点数，该浮点数会自动截断为整数
#  2. 往浮点型数组里插入整数，该整数会自动升级为浮点数

In [4]:
# 整数型数组插入浮点数

import numpy as np

ari = np.array([3,5,7,8])
ari[2] = 99.8
print(ari)


# 浮点数型数组插入整数

arra = np.array([1.1, 4.5, 6.5, 7.8])
arra[-1] = 34
print(arra)

[ 3  5 99  8]
[ 1.1  4.5  6.5 34. ]


In [ ]:
# 3. 共同改变定理
# 如果将两种数据类型的数组进行相互转化呢？


#  整数型数组和浮点型数组相互转化， 规范的方法是使用：
.astype()

In [7]:
import numpy as np

ar = np.array([1,2,3,4,5,6])
print(ar)

ar1 = ar.astype(float)
print(ar1)



[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


In [ ]:
# 只要满足共同改变定理，整数型数组和浮点型数组仍可以相互转化。
# 最常见的是整数型数组在运算过程中升级为浮点型数组

In [11]:
import numpy as np

att = np.array([1 , 3, 5, 7, 9])
print(att)

# 整数型数组与浮点数做运算
print(att + 0.0)
print(att * 1.0)

# 浮点数，作为一个系数，去对数组的每一项都有作用


# 整数型数组遇到除法（即便是除以整数）
print(att / 1)

# 数组除以一个常数，那么这个常数会作用到数组的每一个元素

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
[1. 3. 5. 7. 9.]
[0.33333333 1.         1.66666667 2.33333333 3.        ]


In [13]:
# 整数型数组与浮点型数组做运算

int_ar = np.array([1,3,5])
float_ar = np.array([1.2,3.4,0.1])
print(int_ar + float_ar)

# 两者相加，对应元素，逐元素相加，是它的规则

[2.2 6.4 5.1]


In [ ]:
# 1.2
# 数组维度
# (1) 一维维度 与 二维维度
# —— 不同维度的数组之间，从外形上的本质区别：
# 1. 一维数组使用1层中括号表示
# 2. 二维数组使用2层中括号表示
# 3. 三维数组使用3层中括号表示

In [ ]:
# 有些函数需要传入数组的形状参数，不同维度数组的形状参数为
# 1.一维数组的形状参数形： x 或 (x,)
# 2.二维数组的形状参数形：（x,y)
# 3.三维数组的形状参数形：（x,y,z)

In [ ]:
# 同一个序列进行举例：
# 1. 当数组有1层中括号，如[1 2 3]，则其为一维数组，其形状是3，或者(3，)
# 2. 当数组有2层中括号，如[[1 2 3]], 则为二维数组，其形状是(1,3)
# 3. 当数组有3层中括号，如[[[123]]], 则其为三维数组，其形状是(1,1,3)

In [16]:
np.ones() 
# 此函数可以传入形状参数

AttributeError: module 'numpy' has no attribute 'one'

In [22]:
import numpy as np
arr = np.ones(3) #传入形状3
print(arr) #造出一维数组

arr2 = np.ones((1,3))
print(arr2)


print(arr.shape)

[1. 1. 1.]
[[1. 1. 1.]]
(3,)


In [21]:
# 查看形状：
.shape


# 随时留意数组的维度（通过中括号的数量），后面有些函数（比如数组的拼接函数），需要两个数组为同维度

SyntaxError: invalid syntax (3041882791.py, line 2)

In [ ]:
# (2) 不同维度数组之间的转化
# 一维数组转二维数组，还是二维数组转一维数组，均要使用的是数组的重塑方法：
.reshape()
#该方法需要传入重塑后的形状（shape）参数

# 这个方法下，给定了其他维度的数值，剩下一个维度可以填 -1 ，让他自己去算

In [3]:
import numpy as np

ari = np.arange(10) # 一维数组
print(ari)

arri = ari.reshape(1,-1) # 升级为二维数组
print(arri)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]


In [7]:
import numpy as np
ari = np.arange(10).reshape(2,5) # 2 行 5 列
print(ari)

arri = ari.reshape(-1) # 降为一维数组
print(arri)

# 这里的.reshape()传入的形状参数是 -1，正常情况下是10，这里-1的含义是：
# 反正是一维数组，形状直接自己去算
# 一维数组称为向量 ，二维数组称为矩阵

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
